### ISSUE TITLE
Document python module requirements

### ISSUE THREAD

**Issue by ctgraham** [ulsdevteam/ccvgd-backend#5]
Please document in the README the necessary python modules.

When initially run:
```
$ python app.py runserver -p 8081
Traceback (most recent call last):
  File "app.py", line 2, in <module>
    from manager import create_app
  File "/opt/local/ccvgd/backend/manager.py", line 1, in <module>
    from flask import Flask
ModuleNotFoundError: No module named 'flask'
```

Flask was identified as a dependency.

After installing Flask:
```
$ pip install Flask
```

Re-running the command continues to identify dependencies:
```
$ python app.py runserver -p 8081
Traceback (most recent call last):
  File "app.py", line 2, in <module>
    from manager import create_app
  File "/opt/local/ccvgd/backend/manager.py", line 6, in <module>
    from flask_cors import CORS
```

**Comment by JoyDajunSpaceCraft** [comment]
There is actually a requirments.txt file that contains all modules I used in this project, I will add it in the base dir. Then you can run command pip3 install -r requirments.txt through terminal.

**Comment by ctgraham** [comment]
Are the specific versions required?  Running the install with python 3.8 from RedHat Software Collections terminates with:
```
ERROR: Could not find a version that satisfies the requirement mysql-connector-python==2.0.4 (from -r requirements.txt (line 42)) (from versions: 8.0.5, 8.0.6, 8.0.11, 8.0.12, 8.0.13, 8.0.14, 8.0.15, 8.0.16, 8.0.17, 8.0.18, 8.0.19, 8.0.20, 8.0.21, 8.0.22, 8.0.23, 8.0.24, 8.0.25, 8.0.26)
ERROR: No matching distribution found for mysql-connector-python==2.0.4 (from -r requirements.txt (line 42))
```

Removing just the version requirement for mysql-connector-python ultimately warns:
```
ERROR: jinja2 3.0.1 has requirement MarkupSafe>=2.0, but you'll have markupsafe 1.0 which is incompatible.
ERROR: flask 2.0.1 has requirement click>=7.1.2, but you'll have click 6.7 which is incompatible.
ERROR: flask 2.0.1 has requirement itsdangerous>=2.0, but you'll have itsdangerous 0.24 which is incompatible.
ERROR: flask 2.0.1 has requirement Werkzeug>=2.0, but you'll have werkzeug 0.16.1 which is incompatible.
ERROR: cryptography 3.4.7 has requirement cffi>=1.12, but you'll have cffi 1.10.0 which is incompatible.
```

Removing all version requirements ultimately warns:
```
ERROR: networkx 2.5.1 has requirement decorator<5,>=4.3, but you'll have decorator 5.0.9 which is incompatible.
```

**Comment by ctgraham** [comment]
What version of Flask are you running with?  I don't see Flask itself in the requirements.txt, and I have installed Flask 2.0.1.  Running `python app.py runserver -p 8081` currently returns:
```
Traceback (most recent call last):
  File "app.py", line 6, in <module>
    from flask_script import Manager
  File "/opt/rh/rh-python38/root/usr/local/lib/python3.8/site-packages/flask_scr                                                                                                                                                             ipt/__init__.py", line 15, in <module>
    from flask._compat import text_type
ModuleNotFoundError: No module named 'flask._compat'
```

**Comment by ctgraham** [comment]
I re-tried this under python 3.6, and encountered the same error on `mysql-connector-python`:
```
Collecting mysql-connector-python==2.0.4 (from -r requirements.txt (line 42))
  Could not find a version that satisfies the requirement mysql-connector-python==2.0.4 (from -r requirements.txt (line 42)) (from versions: 8.0.5, 8.0.6, 8.0.11, 8.0.12, 8.0.13, 8.0.14, 8.0.15, 8.0.16, 8.0.17, 8.0.18, 8.0.19, 8.0.20, 8.0.21, 8.0.22, 8.0.23, 8.0.24, 8.0.25, 8.0.26)
No matching distribution found for mysql-connector-python==2.0.4 (from -r requirements.txt (line 42))
```

Allowing `mysql-connector-python` to install 8.0.26 continues, but then halts at:
```
Collecting opencv-python (from -r requirements.txt (line 49))
  Downloading https://files.pythonhosted.org/packages/01/9b/be08992293fb21faf35ab98e06924d7407fcfca89d89c5de65442631556a/opencv-python-4.5.3.56.tar.gz (89.2MB)
    100% |████████████████████████████████| 89.2MB 17kB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-l9bpon9k/opencv-python/setup.py", line 10, in <module>
        import skbuild
    ModuleNotFoundError: No module named 'skbuild'
```

**Comment by JoyDajunSpaceCraft** [comment]
Sorry for my late response, I am moving house and prepare for school recently. 
The problem should be just because I have the wrong opencv-python package added into requirements.txt. I upload the new requirements.txt without opencv-python, this time it should work!

**Comment by ctgraham** [comment]
Using Python 3.6.12 with pip 21.1.3, the build continues to fail with the request for version 2.0.4 of `mysql-connection-python`.  Similarly, the requirement for `Markupsafe==1.0` fails with:
```
ERROR: Could not find a version that satisfies the requirement MarkupSafe==1.0 (from versions: 0.9, 0.9.1, 0.9.2, 0.9.3, 0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.20, 0.21, 0.22, 0.23, 1.0, 1.1.0, 1.1.1, 2.0.0a1, 2.0.0rc1, 2.0.0rc2, 2.0.0, 2.0.1)
ERROR: No matching distribution found for MarkupSafe==1.0
```
Note that version 1.0 does appear in the "from versions" list, however.

Installing the package `wheel`, and removing the specific version requirements for `mysql-connection-python` and `MarkupSafe`, I am able to finish the build.

*Question:* how did you generate this list of required packages?
